name: build-container
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - alpine
          - alpine-edge
          - alpine-3.15.0
          - alpine-3.10
        version: [ 1.2021.15 ]
        include:
          # Can't support on linux/386, linux/arm/v6, linux/arm/v7, and linux/riscv64
          # as no `openjdk-11-jre-headless` available.
          - tag: alpine
            platforms: linux/amd64, linux/arm64/v8, linux/ppc64le, linux/s390x
          - tag: alpine-edge
            platforms: linux/amd64, linux/arm64/v8, linux/ppc64le, linux/s390x
          - tag: alpine-3.15.0
            platforms: linux/amd64, linux/arm64/v8, linux/ppc64le, linux/s390x
          - tag: alpine-3.10
            platforms: linux/amd64, linux/arm64/v8, linux/ppc64le, linux/s390x
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platforms }}
          build-args: |
            BASE_IMAGE=pizzafactory0contorno/piatto:${{ matrix.tag }}
            PLANTUML_VERSION=${{ matrix.version }}
          push: ${{ github.event_name == 'push' }}
          tags: pizzafactory0contorno/plantuml:${{ matrix.version }}_${{ matrix.tag }}
